// <auto-generated />
namespace WUIV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correctifs_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correctifs_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201802160904095_correctifs_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
