// <auto-generated />
namespace WUIV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BDD_Install : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BDD_Install));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151425558_BDD_Install"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
