// <auto-generated />
namespace WUIV2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Correction_BDD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Correction_BDD));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151546055_Correction_BDD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
